// Rebuilds src/fields.js, the field list behind the request builder's $filter helper.
// Reads each API's published OpenAPI document from the B2WTechSupport environment and keeps,
// for every GET that takes OData query options, its fields with a type and a sample value.
//
//   node tools/sync-fields.js            (Node 18+, no npm packages)
//
// Types: s text, n number, b true/false, d date and time, D date, g ID (GUID).
const fs = require('fs');
const path = require('path');

const BASE = 'https://b2w-eus10.b2w.trimble.com/';
const SPECS = { ops: 'OpsAPI_B2WTechSupport/doc/v2/OpsAPI.json', est: 'EstAPI_B2WTechSupport/doc/v1/EstAPI.json', mr: 'MRAPI_B2WTechSupport/doc/v2/MRAPI.json' };
const SKIP = new Set(['$type', 'AntiTamperToken', 'RowVersion']);
const GUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

function typeFromSchema(p) {
  if (!p || p.$ref || p.type === 'array' || p.type === 'object') return null;
  if (p.type === 'boolean') return 'b';
  if (p.type === 'integer' || p.type === 'number') return 'n';
  if (p.type === 'string') return p.format === 'date-time' ? 'd' : p.format === 'date' ? 'D' : p.format === 'uuid' ? 'g' : 's';
  return null;
}
function typeFromValue(v) {
  if (typeof v === 'boolean') return 'b';
  if (typeof v === 'number') return 'n';
  if (typeof v !== 'string') return v === null ? 's' : null;
  if (GUID.test(v)) return 'g';
  if (/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/.test(v)) return 'd';
  if (/^\d{4}-\d{2}-\d{2}$/.test(v)) return 'D';
  return 's';
}
function exampleRecord(get) {
  const r = get.responses && (get.responses['200'] || get.responses[200]);
  const content = r && r.content && Object.values(r.content)[0];
  if (!content || typeof content.example !== 'string') return null;
  try {
    const data = JSON.parse(content.example.trim());
    if (Array.isArray(data)) return data[0] || null;
    if (data && Array.isArray(data.Items)) return data.Items[0] || null;
    return data;
  } catch (e) { return null; }
}
function modelSchema(spec, get) {
  const q = (get.parameters || []).find((p) => p.name === 'queryOptions');
  const ref = q && q.schema && q.schema.$ref;
  const m = ref && /ODataQueryOptions`1\[\[([^,\]]+)/.exec(decodeURIComponent(ref));
  return m && spec.components && spec.components.schemas[m[1]];
}

async function main() {
  const out = {};
  for (const [api, rel] of Object.entries(SPECS)) {
    const res = await fetch(BASE + rel);
    if (!res.ok) throw new Error(rel + ' returned ' + res.status);
    const spec = await res.json();
    out[api] = {};
    for (const [p, ops] of Object.entries(spec.paths)) {
      const get = ops.get;
      if (!get || !(get.parameters || []).some((x) => x.name === 'queryOptions')) continue;
      const props = (modelSchema(spec, get) || {}).properties || {};
      const sample = exampleRecord(get) || {};
      const names = [...new Set(Object.keys(sample).concat(Object.keys(props)))].filter((n) => !SKIP.has(n));
      const fields = [];
      for (const n of names) {
        const t = typeFromSchema(props[n]) || typeFromValue(sample[n]);
        if (!t) continue;   // objects and lists can't be compared in a simple filter
        const v = sample[n];
        const ex = (typeof v === 'string' && v && v.length <= 40) || typeof v === 'number' || typeof v === 'boolean' ? String(v) : '';
        fields.push(ex ? [n, t, ex] : [n, t]);
      }
      if (fields.length) out[api][p] = fields;
    }
    console.log(api + ': ' + Object.keys(out[api]).length + ' endpoints with fields');
  }
  const file = path.join(__dirname, '..', 'src', 'fields.js');
  fs.writeFileSync(file,
    '/* Generated by tools/sync-fields.js from the B2WTechSupport OpenAPI documents on ' + new Date().toISOString().slice(0, 10) + '. Do not edit by hand. */\n' +
    'window.B2W_FIELDS = ' + JSON.stringify(out) + ';\n');
  console.log('Wrote ' + path.relative(process.cwd(), file) + ' (' + Math.round(fs.statSync(file).size / 1024) + ' KB)');
}
main().catch((e) => { console.error(e.message); process.exit(1); });
